# Run build on every push & pr to run qa checks
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run buildCoverage

    - name: Remove node_modules
      run: |
        rm -rf node_modules

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ./
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage
